allowBuilds:
  '@parcel/watcher': false
  '@tailwindcss/oxide': false
  esbuild: false
  lmdb: false
  msgpackr-extract: false
minimumReleaseAgeExclude:
  - '@wawjs/ngx-core@22.0.6'
  - '@wawjs/ngx-translate@22.0.6'
